// src/utils/plugins/ppt_creator.cjs
// Pure Node.js PowerPoint creator using pptxgenjs — NO Python required
'use strict';

const PptxGenJS = require('pptxgenjs');
const fs = require('fs');
const path = require('path');

// Theme palettes: { background, title, text, accent }
const THEMES = {
  professional: { bg: '1F3864', title: 'FFFFFF', text: 'D0D8E8', accent: '4472C4', subBg: '2E4A7A' },
  modern:       { bg: '0F0F1A', title: '00D4FF', text: 'C8C8D8', accent: '7C3AED', subBg: '1A1A2E' },
  creative:     { bg: '1A0A2E', title: 'FF6B9D', text: 'E8D5F5', accent: 'FF6B9D', subBg: '2D1650' },
  minimal:      { bg: 'F8F9FA', title: '1A202C', text: '4A5568', accent: '3182CE', subBg: 'EDF2F7' },
  dark:         { bg: '0D1117', title: '58A6FF', text: '8B949E', accent: '1F6FEB', subBg: '161B22' },
};

async function createPowerPoint({ file_path, title = 'Presentation', slides = [], theme = 'professional' }) {
  let targetPath = file_path.endsWith('.pptx') ? file_path : `${file_path}.pptx`;
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });

  const palette = THEMES[theme] || THEMES.professional;
  const pptx = new PptxGenJS();

  // Slide dimensions: widescreen 16:9
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author  = 'Alsa AI';
  pptx.company = 'Zentryx Tech Solutions';
  pptx.subject = title;
  pptx.title   = title;

  // ── TITLE SLIDE ──────────────────────────────────────────────────────────────
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: palette.bg };

  // Top accent bar
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: palette.accent } });

  // Centered title
  titleSlide.addText(title, {
    x: 0.5, y: 2.5, w: 12.33, h: 1.5,
    fontSize: 44, bold: true, color: palette.title,
    align: 'center', fontFace: 'Calibri',
  });

  // Subtitle bar
  titleSlide.addShape(pptx.ShapeType.rect, { x: 4, y: 4.2, w: 5.33, h: 0.06, fill: { color: palette.accent } });

  // Generated-by text
  titleSlide.addText('Generated by Alsa AI · Zentryx Tech Solutions', {
    x: 0.5, y: 4.5, w: 12.33, h: 0.5,
    fontSize: 14, color: palette.text, align: 'center', italic: true,
  });

  // Bottom accent bar
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 7.42, w: '100%', h: 0.08, fill: { color: palette.accent } });

  // ── CONTENT SLIDES ───────────────────────────────────────────────────────────
  slides.forEach((slide, idx) => {
    const s = pptx.addSlide();
    s.background = { color: palette.subBg };

    // Slide number bubble
    s.addText(String(idx + 1), {
      x: 12.0, y: 0.1, w: 0.5, h: 0.5,
      fontSize: 12, color: palette.title, align: 'center',
      fill: { color: palette.accent }, shape: pptx.ShapeType.ellipse,
    });

    // Header bar
    s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 1.1, fill: { color: palette.bg } });
    s.addShape(pptx.ShapeType.rect, { x: 0, y: 1.05, w: '100%', h: 0.06, fill: { color: palette.accent } });

    // Slide title
    const slideTitle = slide.title || `Slide ${idx + 1}`;
    s.addText(slideTitle, {
      x: 0.4, y: 0.1, w: 11.5, h: 0.9,
      fontSize: 28, bold: true, color: palette.title, fontFace: 'Calibri',
    });

    // Content body
    const rawContent = slide.content || '';
    const lines = rawContent.split(/\n/).filter(l => l.trim().length > 0);

    if (lines.length > 0) {
      // Build rich text with bullet points
      const textObj = lines.map(line => {
        const isBullet = line.trimStart().startsWith('-') || line.trimStart().startsWith('•');
        const cleanLine = line.replace(/^[\s\-•]+/, '').trim();
        return {
          text: cleanLine,
          options: {
            bullet: isBullet ? { type: 'bullet' } : false,
            fontSize: 20,
            color: palette.text,
            fontFace: 'Calibri',
            breakLine: true,
          },
        };
      });

      s.addText(textObj, {
        x: 0.4, y: 1.3, w: 12.1, h: 6.0,
        valign: 'top', wrap: true,
      });
    }

    // Footer line
    s.addShape(pptx.ShapeType.rect, { x: 0, y: 7.42, w: '100%', h: 0.08, fill: { color: palette.accent } });
    s.addText(title, {
      x: 0.4, y: 7.35, w: 8, h: 0.2,
      fontSize: 9, color: palette.text, italic: true,
    });
  });

  // Save file
  await pptx.writeFile({ fileName: targetPath });
  return { success: true, message: `PowerPoint created: ${targetPath}`, file_path: targetPath };
}

// CLI entry
if (require.main === module) {
  const input = JSON.parse(process.argv[2] || '{}');
  createPowerPoint(input)
    .then(res => console.log(JSON.stringify(res)))
    .catch(err => console.log(JSON.stringify({ success: false, error: err.message })));
}

module.exports = { createPowerPoint };